### ISSUE TITLE
How to handle pseudopotentials

### ISSUE THREAD

**Issue by gbrunin** [abinit/atomate#3]
Following the discussion about pseudopotentials, I'm opening this issue to keep track of suggestions, different options, etc. 

Basically, the pseudos will be specified in the abinit input file with [pseudos](https://docs.abinit.org/variables/files/#pseudos) and [pp_dirpath](https://docs.abinit.org/variables/files/#pp_dirpath), starting with abinit v9. Compatibility with v8 and the .files file is not planned as it is meant to disappear in future releases.

At the python level, let me quote David: 

> we have different options. For pseudos from the pseudo-dojo, we could use a string identifier corresponding to a specific PD table/xc/version etc ... for a given atom. This will need a few changes in the pseudo_dojo package as well but it is worth it (there are some drawbacks with the current situation). [...] We also need to allow for custom pseudos.

**Comment by davidwaroquiers** [comment]
Closing as double with #2 (sorry I added it in the meantime).
